name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  scala_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

  jest_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: 'sbt'
      - name: Update sbt
        run: sbt update
      - name: ScalaJS build
        run: npm run build:scala:fast
      - name: Run Jest tests
        run: npm test

  build_and_deploy:
    needs: [scala_ci, jest_ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: 'sbt'
      - name: Update sbt
        run: sbt update
      - name: NPM install
        run: npm install
      - name: Scala.JS Build
        run: npm run build:scala
      - name: NPM Build
        run: npm run build:webpack
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
